export const API_KEY =
  "live_k77YJ1Sa3RsUfqEwbuKzrsevPSBW7iCoeeTZKSuj0ahl51TyYwbMXoLhVwwyIIvF";

export const VALUES = {
  IMAGE_LIMIT_COUNT: 30,
  BREAKPOINT_XLARGE: 960,
  BREAKPOINT_LARGE: 500,
  ANIMATION_TIMING_SHORT: 300,
  ANIMATION_DELAY_100: 100,
};
